### ISSUE TITLE
Pick a theme

### ISSUE THREAD

**Issue by dentarg** [twingly/blog#3]
I looked through http://jekyllthemes.org/ and found these that I like:

* http://demo.getpoole.com/
* https://kiko.gfjaru.com/
* http://rosario.io/2013/11/10/kasper-theme-for-jekyll.html

@twingly/dev anyone else having some suggestions?

**Comment by jage** [comment]
I vote for Kasper.

**Comment by roback** [comment]
Kasper has my vote too.
